; monochrome palette color ids
	const_def
	const SHADE_WHITE ; %00
	const SHADE_LIGHT ; %01
	const SHADE_DARK  ; %10
	const SHADE_BLACK ; %11
DEF NUM_PAL_COLORS EQU const_value

DEF PAL_COLOR_SIZE EQU 2
DEF PALETTE_SIZE EQU NUM_PAL_COLORS * PAL_COLOR_SIZE

; pal/blk packets
; SetPalFunctions indexes (see engine/gfx/palettes.asm)
	const_def
	const SET_PAL_BATTLE_BLACK         ; $00
	const SET_PAL_BATTLE               ; $01
	const SET_PAL_TOWN_MAP             ; $02
	const SET_PAL_STATUS_SCREEN        ; $03
	const SET_PAL_POKEDEX              ; $04
	const SET_PAL_SLOTS                ; $05
	const SET_PAL_TITLE_SCREEN         ; $06
	const SET_PAL_NIDORINO_INTRO       ; $07
	const SET_PAL_GENERIC              ; $08
	const SET_PAL_OVERWORLD            ; $09
	const SET_PAL_PARTY_MENU           ; $0A
	const SET_PAL_POKEMON_WHOLE_SCREEN ; $0B
	const SET_PAL_GAME_FREAK_INTRO     ; $0C
	const SET_PAL_TRAINER_CARD         ; $0D

DEF SET_PAL_PARTY_MENU_HP_BARS EQU $fc
DEF SET_PAL_DEFAULT EQU $ff

; sgb palettes
; SuperPalettes indexes (see data/sgb/sgb_palettes.asm)
	const_def
	const PAL_ROUTE     ; $00
	const PAL_PALLET    ; $01
	const PAL_VIRIDIAN  ; $02
	const PAL_PEWTER    ; $03
	const PAL_CERULEAN  ; $04
	const PAL_LAVENDER  ; $05
	const PAL_VERMILION ; $06
	const PAL_CELADON   ; $07
	const PAL_FUCHSIA   ; $08
	const PAL_CINNABAR  ; $09
	const PAL_INDIGO    ; $0A
	const PAL_SAFFRON   ; $0B
	const PAL_TOWNMAP   ; $0C
	const PAL_LOGO1     ; $0D
	const PAL_LOGO2     ; $0E
	const PAL_0F        ; $0F
	const PAL_MEWMON    ; $10
	const PAL_BLUEMON   ; $11
	const PAL_REDMON    ; $12
	const PAL_CYANMON   ; $13
	const PAL_PURPLEMON ; $14
	const PAL_BROWNMON  ; $15
	const PAL_GREENMON  ; $16
	const PAL_PINKMON   ; $17
	const PAL_YELLOWMON ; $18
	const PAL_GREYMON   ; $19
	const PAL_AMARANTH  ; [TODO) shift values
	const PAL_SLOTS1    ; $1A
	const PAL_SLOTS2    ; $1B
	const PAL_SLOTS3    ; $1C
	const PAL_SLOTS4    ; $1D
	const PAL_BLACK     ; $1E
	const PAL_GREENBAR  ; $1F
	const PAL_YELLOWBAR ; $20
	const PAL_REDBAR    ; $21
	const PAL_BADGE     ; $22
	const PAL_CAVE      ; $23
	const PAL_GAMEFREAK ; $24
	; POKEMON PALETTES
	const PAL_MISSINGNO  ; 0
	const PAL_BULBASAUR  ; 1
	const PAL_IVYSAUR    ; 2
	const PAL_VENUSAUR   ; 3
	const PAL_CHARMANDER ; 4
	const PAL_CHARMELEON ; 5
	const PAL_CHARIZARD  ; 6
	const PAL_SQUIRTLE   ; 7
	const PAL_WARTORTLE  ; 8
	const PAL_BLASTOISE  ; 9
	const PAL_CATERPIE   ; 10
	const PAL_METAPOD    ; 11
	const PAL_BUTTERFREE ; 12
	const PAL_WEEDLE     ; 13
	const PAL_KAKUNA     ; 14
	const PAL_BEEDRILL   ; 15
	const PAL_PIDGEY     ; 16
	const PAL_PIDGEOTTO  ; 17
	const PAL_PIDGEOT    ; 18
	const PAL_RATTATA    ; 19
	const PAL_RATICATE   ; 20
	const PAL_SPEAROW    ; 21
	const PAL_FEAROW     ; 22
	const PAL_EKANS      ; 23
	const PAL_ARBOK      ; 24
	const PAL_PIKACHU    ; 25
	const PAL_RAICHU     ; 26
	const PAL_SANDSHREW  ; 27
	const PAL_SANDSLASH  ; 28
	const PAL_NIDORAN_F  ; 29
	const PAL_NIDORINA   ; 30
	const PAL_NIDOQUEEN  ; 31
	const PAL_NIDORAN_M  ; 32
	const PAL_NIDORINO   ; 33
	const PAL_NIDOKING   ; 34
	const PAL_CLEFAIRY   ; 35
	const PAL_CLEFABLE   ; 36
	const PAL_VULPIX     ; 37
	const PAL_NINETALES  ; 38
	const PAL_JIGGLYPUFF ; 39
	const PAL_WIGGLYTUFF ; 40
	const PAL_ZUBAT      ; 41
	const PAL_GOLBAT     ; 42
	const PAL_ODDISH     ; 43
	const PAL_GLOOM      ; 44
	const PAL_VILEPLUME  ; 45
	const PAL_PARAS      ; 46
	const PAL_PARASECT   ; 47
	const PAL_VENONAT    ; 48
	const PAL_VENOMOTH   ; 49
	const PAL_DIGLETT    ; 50
	const PAL_DUGTRIO    ; 51
	const PAL_MEOWTH     ; 52
	const PAL_PERSIAN    ; 53
	const PAL_PSYDUCK    ; 54
	const PAL_GOLDUCK    ; 55
	const PAL_MANKEY     ; 56
	const PAL_PRIMEAPE   ; 57
	const PAL_GROWLITHE  ; 58
	const PAL_ARCANINE   ; 59
	const PAL_POLIWAG    ; 60
	const PAL_POLIWHIRL  ; 61
	const PAL_POLIWRATH  ; 62
	const PAL_ABRA       ; 63
	const PAL_KADABRA    ; 64
	const PAL_ALAKAZAM   ; 65
	const PAL_MACHOP     ; 66
	const PAL_MACHOKE    ; 67
	const PAL_MACHAMP    ; 68
	const PAL_BELLSPROUT ; 69
	const PAL_WEEPINBELL ; 70
	const PAL_VICTREEBEL ; 71
	const PAL_TENTACOOL  ; 72
	const PAL_TENTACRUEL ; 73
	const PAL_GEODUDE    ; 74
	const PAL_GRAVELER   ; 75
	const PAL_GOLEM      ; 76
	const PAL_PONYTA     ; 77
	const PAL_RAPIDASH   ; 78
	const PAL_SLOWPOKE   ; 79
	const PAL_SLOWBRO    ; 80
	const PAL_MAGNEMITE  ; 81
	const PAL_MAGNETON   ; 82
	const PAL_FARFETCHD  ; 83
	const PAL_DODUO      ; 84
	const PAL_DODRIO     ; 85
	const PAL_SEEL       ; 86
	const PAL_DEWGONG    ; 87
	const PAL_GRIMER     ; 88
	const PAL_MUK        ; 89
	const PAL_SHELLDER   ; 90
	const PAL_CLOYSTER   ; 91
	const PAL_GASTLY     ; 92
	const PAL_HAUNTER    ; 93
	const PAL_GENGAR     ; 94
	const PAL_ONIX       ; 95
	const PAL_DROWZEE    ; 96
	const PAL_HYPNO      ; 97
	const PAL_KRABBY     ; 98
	const PAL_KINGLER    ; 99
	const PAL_VOLTORB    ; 100
	const PAL_ELECTRODE  ; 101
	const PAL_EXEGGCUTE  ; 102
	const PAL_EXEGGUTOR  ; 103
	const PAL_CUBONE     ; 104
	const PAL_MAROWAK    ; 105
	const PAL_HITMONLEE  ; 106
	const PAL_HITMONCHAN ; 107
	const PAL_LICKITUNG  ; 108
	const PAL_KOFFING    ; 109
	const PAL_WEEZING    ; 110
	const PAL_RHYHORN    ; 111
	const PAL_RHYDON     ; 112
	const PAL_CHANSEY    ; 113
	const PAL_TANGELA    ; 114
	const PAL_KANGASKHAN ; 115
	const PAL_HORSEA     ; 116
	const PAL_SEADRA     ; 117
	const PAL_GOLDEEN    ; 118
	const PAL_SEAKING    ; 119
	const PAL_STARYU     ; 120
	const PAL_STARMIE    ; 121
	const PAL_MR_MIME    ; 122
	const PAL_SCYTHER    ; 123
	const PAL_JYNX       ; 124
	const PAL_ELECTABUZZ ; 125
	const PAL_MAGMAR     ; 126
	const PAL_PINSIR     ; 127
	const PAL_TAUROS     ; 128
	const PAL_MAGIKARP   ; 129
	const PAL_GYARADOS   ; 130
	const PAL_LAPRAS     ; 131
	const PAL_DITTO      ; 132
	const PAL_EEVEE      ; 133
	const PAL_VAPOREON   ; 134
	const PAL_JOLTEON    ; 135
	const PAL_FLAREON    ; 136
	const PAL_PORYGON    ; 137
	const PAL_OMANYTE    ; 138
	const PAL_OMASTAR    ; 139
	const PAL_KABUTO     ; 140
	const PAL_KABUTOPS   ; 141
	const PAL_AERODACTYL ; 142
	const PAL_SNORLAX    ; 143
	const PAL_ARTICUNO   ; 144
	const PAL_ZAPDOS     ; 145
	const PAL_MOLTRES    ; 146
	const PAL_DRATINI    ; 147
	const PAL_DRAGONAIR  ; 148
	const PAL_DRAGONITE  ; 149
	const PAL_MEWTWO     ; 150
	const PAL_MEW        ; 151
DEF NUM_SGB_PALS EQU const_value
