; pokedex ids
; indexes for:
; - BaseStats (see data/pokemon/base_stats.asm)
; - MonPartyData (see data/pokemon/menu_icons.asm)
; - MonsterPalettes (see data/pokemon/palettes.asm)
	const_def 1
	const DEX_BULBASAUR  ; 1
	const DEX_IVYSAUR    ; 2
	const DEX_VENUSAUR   ; 3
	const DEX_CHARMANDER ; 4
	const DEX_CHARMELEON ; 5
	const DEX_CHARIZARD  ; 6
	const DEX_SQUIRTLE   ; 7
	const DEX_WARTORTLE  ; 8
	const DEX_BLASTOISE  ; 9
	const DEX_RATTATA    ; 10
	const DEX_RATICATE   ; 11
	const DEX_PIDGEY     ; 12
	const DEX_PIDGEOTTO  ; 13
	const DEX_PIDGEOT    ; 14
	const DEX_SPEAROW    ; 15
	const DEX_FEAROW     ; 16
	const DEX_EXEGGCUTE  ; 17
	const DEX_EXEGGUTOR  ; 18
	const DEX_NIDORAN_F  ; 19
	const DEX_NIDORINA   ; 20
	const DEX_NIDOQUEEN  ; 21
	const DEX_NIDORAN_M  ; 22
	const DEX_NIDORINO   ; 23
	const DEX_NIDOKING   ; 24
	const DEX_MEOWTH     ; 25
	const DEX_PERSIAN    ; 26
	const DEX_PSYDUCK    ; 27
	const DEX_GOLDUCK    ; 28
	const DEX_MANKEY     ; 29
	const DEX_PRIMEAPE   ; 30
	const DEX_VENONAT    ; 31
	const DEX_VENOMOTH   ; 32
	const DEX_GROWLITHE  ; 33
	const DEX_ARCANINE   ; 34
	const DEX_CATERPIE   ; 35
	const DEX_METAPOD    ; 36
	const DEX_BUTTERFREE ; 37
	const DEX_WEEDLE     ; 38
	const DEX_KAKUNA     ; 39
	const DEX_BEEDRILL   ; 40
	const DEX_PIKACHU    ; 41
	const DEX_RAICHU     ; 42
	const DEX_VULPIX     ; 43
	const DEX_NINETALES  ; 44
	const DEX_JIGGLYPUFF ; 45
	const DEX_WIGGLYTUFF ; 46
	const DEX_ZUBAT      ; 47
	const DEX_GOLBAT     ; 48
	const DEX_GEODUDE    ; 49
	const DEX_GRAVELER   ; 50
	const DEX_GOLEM      ; 51
	const DEX_PARAS      ; 52
	const DEX_PARASECT   ; 53
	const DEX_CLEFAIRY   ; 54
	const DEX_CLEFABLE   ; 55
	const DEX_RHYHORN    ; 56
	const DEX_RHYDON     ; 57
	const DEX_SANDSHREW  ; 58
	const DEX_SANDSLASH  ; 59
	const DEX_POLIWAG    ; 60
	const DEX_POLIWHIRL  ; 61
	const DEX_POLIWRATH  ; 62
	const DEX_EKANS      ; 63
	const DEX_ARBOK      ; 64
	const DEX_FARFETCHD  ; 65
	const DEX_ODDISH     ; 66
	const DEX_GLOOM      ; 67
	const DEX_VILEPLUME  ; 68
	const DEX_BELLSPROUT ; 69
	const DEX_WEEPINBELL ; 70
	const DEX_VICTREEBEL ; 71
	const DEX_EEVEE      ; 72
	const DEX_VAPOREON   ; 73
	const DEX_JOLTEON    ; 74
	const DEX_FLAREON    ; 75
	const DEX_ABRA       ; 76
	const DEX_KADABRA    ; 77
	const DEX_ALAKAZAM   ; 78
	const DEX_GOLDEEN    ; 79
	const DEX_SEAKING    ; 80
	const DEX_STARYU     ; 81
	const DEX_STARMIE    ; 82
	const DEX_SLOWPOKE   ; 83
	const DEX_SLOWBRO    ; 84
	const DEX_TANGELA    ; 85
	const DEX_LICKITUNG  ; 86
	const DEX_SHELLDER   ; 87
	const DEX_CLOYSTER   ; 88
	const DEX_PONYTA     ; 89
	const DEX_RAPIDASH   ; 90
	const DEX_DROWZEE    ; 91
	const DEX_HYPNO      ; 92
	const DEX_DODUO      ; 93
	const DEX_DODRIO     ; 94
	const DEX_MAGNEMITE  ; 95
	const DEX_MAGNETON   ; 96
	const DEX_DIGLETT    ; 97
	const DEX_DUGTRIO    ; 98
	const DEX_TAUROS     ; 99
	const DEX_MACHOP     ; 100
	const DEX_MACHOKE    ; 101
	const DEX_MACHAMP    ; 102
	const DEX_HITMONLEE  ; 103
	const DEX_HITMONCHAN ; 104
	const DEX_MR_MIME    ; 105
	const DEX_MAGIKARP   ; 106
	const DEX_GYARADOS   ; 107
	const DEX_GRIMER     ; 108
	const DEX_MUK        ; 109
	const DEX_KOFFING    ; 110
	const DEX_WEEZING    ; 111
	const DEX_PORYGON    ; 112
	const DEX_GASTLY     ; 113
	const DEX_HAUNTER    ; 114
	const DEX_GENGAR     ; 115
	const DEX_CUBONE     ; 116
	const DEX_MAROWAK    ; 117
	const DEX_CHANSEY    ; 118
	const DEX_VOLTORB    ; 119
	const DEX_ELECTRODE  ; 120
	const DEX_PINSIR     ; 121
	const DEX_SCYTHER    ; 122
	const DEX_DITTO      ; 123
	const DEX_HORSEA     ; 124
	const DEX_SEADRA     ; 125
	const DEX_ONIX       ; 126
	const DEX_KANGASKHAN ; 127
	const DEX_ELECTABUZZ ; 128
	const DEX_SNORLAX    ; 129
	const DEX_TENTACOOL  ; 130
	const DEX_TENTACRUEL ; 131
	const DEX_KRABBY     ; 132
	const DEX_KINGLER    ; 133
	const DEX_LAPRAS     ; 134
	const DEX_JYNX       ; 135
	const DEX_SEEL       ; 136
	const DEX_DEWGONG    ; 137
	const DEX_MAGMAR     ; 138
	const DEX_OMANYTE    ; 139
	const DEX_OMASTAR    ; 140
	const DEX_KABUTO     ; 141
	const DEX_KABUTOPS   ; 142
	const DEX_AERODACTYL ; 143
	const DEX_DRATINI    ; 144
	const DEX_DRAGONAIR  ; 145
	const DEX_DRAGONITE  ; 146
	const DEX_ARTICUNO   ; 147
	const DEX_ZAPDOS     ; 148
	const DEX_MOLTRES    ; 149
	const DEX_MEWTWO     ; 150
	const DEX_MEW        ; 151

DEF NUM_POKEMON EQU const_value - 1
