CeruleanLesbianHouse_Script:
	jp EnableAutoTextBoxDrawing

CeruleanLesbianHouse_TextPointers:
	def_text_pointers
	dw_const CeruleanLesbianHouseBeautyText,  TEXT_CERULEANLESBIANHOUSE_BEAUTY
	dw_const CeruleanLesbianHouseBrunetteGirlText, TEXT_CERULEANLESBIANHOUSE_BRUNETTE_GIRL

CeruleanLesbianHouseBeautyText:
	text_far _CeruleanLesbianHouseBeautyText
	text_end

CeruleanLesbianHouseBrunetteGirlText:
	text_far _CeruleanLesbianHouseBrunetteGirlText
	text_end
